manifest:
  version: "0.10"
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.1.0      # Nur den Tag verwenden
      import: true
  self:
    path: .
